/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vdbk.apps.quanlybanhang.ui;

import com.vdbk.apps.quanlybanhang.bill.BillPanel;
import com.vdbk.apps.quanlybanhang.depot.DepotPanel;
import com.vdbk.apps.quanlybanhang.bill.SellPanel;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author DucNV23
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public Main() throws UnknownHostException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws UnknownHostException {
        setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();

        jHeader = new JLabel();
        jHeader.setHorizontalAlignment(SwingConstants.CENTER);
        jHeader.setVerticalAlignment(SwingConstants.CENTER);
        jHeader.setFont(Constants.FONT_HEADER);
        jHeader.setText("KHO HÀNG");

        jTabbedPane1 = new javax.swing.JTabbedPane();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(Constants.FONT_TITLE);
       

        JButton btnMinimize = new JButton("_");
        JButton btnClose = new JButton("X");

        JPanel panel = new JPanel();
        c.weightx = 1.0;
        c.gridx = 0;
        c.gridy = 0;
        add(panel, c);

        JLabel tf = new JLabel("Version: " + Constants.VERSION);
        c.insets = new Insets(10, 5, 5, 10);
        c.weightx = 0.0;
        c.fill = GridBagConstraints.HORIZONTAL;
        c.gridx = 0;
        c.gridy = 0;
        add(tf, c);

        c.insets = new Insets(10, 5, 5, 5);
        c.weightx = 0.0;
        c.gridx = 1;
        c.gridy = 0;
        add(btnMinimize, c);
        c.insets = new Insets(10, 5, 5, 10);
        c.weightx = 0.0;
        c.gridx = 2;
        c.gridy = 0;
        add(btnClose, c);

        c.insets = new Insets(20, 0, 0, 0);
        //  c.weightx = 1.0;
        c.fill = GridBagConstraints.HORIZONTAL;
        c.gridx = 0;
        c.gridy = 0;
        c.gridwidth = 3;
        c.gridheight = 1;
        add(jHeader, c);

        c.insets = new Insets(10, 10, 10, 10);
        c.fill = GridBagConstraints.BOTH;
        //  c.weightx = 1.0;
        c.weighty = 1.0;
        c.gridwidth = 3;
        c.gridx = 0;
        c.gridy = 1;
        add(jTabbedPane1, c);

        /* add three tab with three JPanel */
        SellPanel sell = new SellPanel(this);
        DepotPanel depot = new DepotPanel(this);
        BillPanel bill = new BillPanel(this);

        jTabbedPane1.addTab("BÁN HÀNG", null, sell, "click to show panel 2");
        jTabbedPane1.addTab("KHO", null, depot, "click to show panel 1");
        jTabbedPane1.addTab("HÓA ĐƠN", null, bill, "");
        //default tab is bill
        jTabbedPane1.setSelectedIndex(0);
        sell.requestFocus();
        jHeader.setText("HÓA ĐƠN BÁN HÀNG");

        jTabbedPane1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (jTabbedPane1 == null && jHeader == null) {
                    return;
                }
                switch (jTabbedPane1.getSelectedIndex()) {
                    case 0:
                        jHeader.setText("HÓA ĐƠN BÁN HÀNG");
                        sell.requestFocus();
                        break;
                    case 1:
                        jHeader.setText("KHO HÀNG");
                        depot.requestFocus();
                        sell.clearSearch();
                        break;
                    case 2:
                        jHeader.setText("HÓA ĐƠN");

                        sell.clearSearch();
                        break;
                    default:
                        break;
                }
            }
        });

        btnMinimize.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                minimizeApplication();
            }
        });

        btnClose.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                closeApplication();
            }
        });

    }// </editor-fold>         

    private void minimizeApplication() {
        this.setState(Frame.ICONIFIED);
    }

    private void closeApplication() {
        Object[] options = {"Có",
            "Không"};
        int result = JOptionPane.showOptionDialog(
                this,
                "Bạn có chắc muốn thoát khỏi chương trình",
                "Chú ý",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, //do not use a custom Icon
                options, //the titles of buttons
                options[0]);
        if (result == JOptionPane.OK_OPTION) {
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main frame;
                try {
                    frame = new Main();
                    frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    frame.dispose();
                    frame.setUndecorated(true);
                    frame.setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTabbedPane jTabbedPane1;
    private JLabel jHeader;
    // End of variables declaration                   
}
