/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vdbk.apps.quanlybanhang.depot;

import com.vdbk.apps.quanlybanhang.barcode.utils.Utils;
import com.vdbk.apps.quanlybanhang.database.Item;
import com.vdbk.apps.quanlybanhang.ui.Constants;
import com.vdbk.apps.quanlybanhang.ui.JTableButton;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DucNV23
 */
public class DepotTable extends javax.swing.JPanel {

    private int itemCount = 0;
    private ArrayList<Item> items = new ArrayList<Item>();
    private ItemSelectionListener listener;

    void update(String barcode, Item newItem) {
        for (int i = 0; i < items.size(); i++) {
            if (items.get(i).getId().equals(barcode)) {
                String wsInformation = "";
                if (newItem.getRetailMaxNumber() > 0) {
                    wsInformation = Utils.fmt(newItem.getWholeScalePrice()) + " / " + newItem.getRetailMaxNumber() + newItem.getUnit();
                }
                jTable1.setValueAt(newItem.getName(), i, 1);
                jTable1.setValueAt(wsInformation, i, 2);
                jTable1.setValueAt(newItem.getRetailPrice(), i, 3);
                jTable1.setValueAt(newItem.getUnit(), i, 4);
                jTable1.setValueAt(newItem.getNote(), i, 5);
                items.remove(i);
                items.add(i, newItem);
                scrollToIndex(i);
                break;
            }
        }
    }

    public void scrollToItem(String barcode) {
        for (int i = 0; i < items.size(); i++) {
            if (items.get(i).getId().equals(barcode)) {
                scrollToIndex(i);
                break;
            }
        }
    }

    public void delete(String barcode) {
        for (int i = 0; i < items.size(); i++) {
            if (items.get(i).getId().equals(barcode)) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(i);
                items.remove(i);
                break;
            }
        }
    }

    public interface ItemSelectionListener {

        public void onItemSelected(Item item);//mouse clicked

        public void onItemEntered(Item item);// mouse double clicked

        public void onDeleteItemClicked(Item item);
    }

    /**
     * Creates new form Table
     */
    public DepotTable() {
        initComponents();
        jTable1.getColumnModel().getColumn(0).setMaxWidth(Constants.ITEM_INDEX_WIDTH);//stt
        jTable1.getColumnModel().getColumn(0).setMinWidth(Constants.ITEM_INDEX_WIDTH);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(Constants.ITEM_NAME_WIDTH);//ten hang
        jTable1.getColumnModel().getColumn(1).setMinWidth(Constants.ITEM_NAME_WIDTH);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(Constants.ITEM_PRICE_WIDTH * 2);//gia si
        jTable1.getColumnModel().getColumn(2).setMinWidth(Constants.ITEM_PRICE_WIDTH * 2);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(Constants.ITEM_PRICE_WIDTH);//gia le
        jTable1.getColumnModel().getColumn(3).setMinWidth(Constants.ITEM_PRICE_WIDTH);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(Constants.ITEM_UNIT_WIDTH);//don vi
        jTable1.getColumnModel().getColumn(4).setMinWidth(Constants.ITEM_UNIT_WIDTH);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(Constants.ITEM_BTN_DEL_WIDTH);//delete
        jTable1.getColumnModel().getColumn(6).setMinWidth(Constants.ITEM_BTN_DEL_WIDTH);
        jTable1.getTableHeader().setFont(Constants.FONT_CONTENT);
        jTable1.setFont(Constants.FONT_CONTENT);
        jTable1.setShowGrid(true);
    }

    public void addItemSelectionListener(ItemSelectionListener listener) {
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setFont(Constants.FONT_CONTENT);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "STT", "TÊN HÀNG", "GIÁ BÁN SỈ", "GIÁ BÁN LẺ", "ĐƠN VỊ", "GHI CHÚ", ""
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.Double.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.Object.class

            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }

            @Override
            public Object getValueAt(int row, int column) {
                if (column == 6) {
                    JButton button = new JButton("");
                    button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear_24.png"))); // NOI18N

                    button.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent arg0) {
                            //delete row bill item
                            Item item = items.get(row);
                            listener.onDeleteItemClicked(item);
                        }
                    });
                    return button;
                } else {
                    return super.getValueAt(row, column); //To change body of generated methods, choose Tools | Templates.
                }
            }

        });
        jTable1.getColumnModel().getColumn(6).setCellRenderer(new JTableButton.JTableButtonRenderer());
        //jTable1.addMouseListener(new JTableButton.JTableButtonMouseListener(jTable1));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(Constants.TABLE_ROW_HEIGHT);
        jTable1.setRowMargin(Constants.TABLE_ROW_MARGIN);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if (listener == null) {
            return;
        }
        JTable table = (JTable) evt.getSource();
        Point point = evt.getPoint();
        int row = table.rowAtPoint(point);
        int column = table.getColumnModel().getColumnIndexAtX(evt.getX());
        if (table.getSelectedRow() < 0) {
            return;
        }

        Object value = table.getValueAt(row, column);
        if (value instanceof JButton) {
            /*perform a click event*/
            ((JButton) value).doClick();
            return;
        }

        Item item = items.get(table.getSelectedRow());

        if (evt.getClickCount() == 2) {
            listener.onItemEntered(item);
        } else {
            listener.onItemSelected(item);
        }
    }

    public void addNewItem(Item item) {
        if (item == null) {
            return;
        }
        itemCount++;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String wsInformation = "";
        if (item.getRetailMaxNumber() > 0) {
            wsInformation = Utils.fmt(item.getWholeScalePrice()) + " / " + item.getRetailMaxNumber() + item.getUnit();
        }
        model.addRow(new Object[]{itemCount, item.getName(), wsInformation, item.getRetailPrice(), item.getUnit(), item.getNote()});
        items.add(item);
    }

    private void scrollToIndex(int index) {
        jTable1.setRowSelectionInterval(index, index);
        jTable1.scrollRectToVisible(new Rectangle(jTable1.getCellRect(index, 0, true)));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
